spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:cardsDb
    username: hamedmiri72
    password: hamedmiri72
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active: "qa"

server:
  port: 9092


build:
  version: "V3.0"

cards:
  message: "Account service"
  contactDetails:
    name: Hamed MIRI
    email: hamedmiri72@gmail.com
  onCallSupport:
    - 735 584 8222
    - 735 584 8221