services:
  accounts:
    image: hamedmiri72/accounts:s4
    container_name: "accounts"
    ports:
      - 9090:9090
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank


  cards:
    image: hamedmiri72/cards:s4
    container_name: "cards"
    ports:
      - 9092:9092
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  loans:
    image: hamedmiri72/loans:s4
    container_name: "loans"
    ports:
      - 9091:9091
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

networks:
  bank:
    driver: "bridge"