services:
  accounts:
    image: hamedmiri72/accounts:s6
    container_name: "accounts"
    ports:
      - 9090:9090
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbitmq"




  cards:
    image: hamedmiri72/cards:s6
    container_name: "cards"
    ports:
      - 9092:9092
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbitmq"



  loans:
    image: hamedmiri72/loans:s6
    container_name: "loans"
    ports:
      - 9091:9091
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbitmq"

  configserver:
    image: hamedmiri72/configserver:s6
    container_name: "configserver"
    ports:
      - 8071:8071
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

networks:
  bank:
    driver: "bridge"

