spring:
  application:
    name: accounts
  data:
  datasource:
    url: jdbc:h2:mem:testdb
    username: hamedmiri72
    password: hamedmiri72
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "qa"
server:
  port: 9090

build:
  version: "V3.0"

accounts:
  message: "Hello from accounts service"
  contactDetails:
    email: "hamedmiri72@gmail.com"
    phone: "123456789"
  onCallSupport:
    - 735 584 8222
    - 735 584 8223

